#!/usr/bin/env python3
"""
STANAG 4285 known symbols of one 256-symbol frame: the 80 sync symbols and the 48 probe symbols.

Written by Claude (Anthropic AI) for Mike Burns, AB1LD, 2026-10-07, for Nils Schiffhauer, DK8OK.

Where the values come from
  * Sync (symbols 0-79): the 31-bit PN sequence, repeated (31 + 31 + 18 symbols), BPSK (+1/-1). We derived it in
    September 2026 from our own recordings by symbol decisions (it is an m-sequence of x^5 + x^2 + 1); it matches
    DK8OK's PN31 bit string. Written out below as bits.
  * Probes (symbols 112-127, 160-175, 208-223): the frame's 176 data/probe positions are scrambled by a 9-stage
    shift register, polynomial x^9 + x^4 + 1, loaded with all ones at the start of each frame's data part and
    clocked three times per symbol; the three lowest register bits give an 8PSK index 0-7 that is added (mod 8) to
    the symbol. Probe symbols carry index 0 before scrambling, so after scrambling they ARE the scrambler output at
    data positions 32-47, 80-95 and 128-143. They are therefore identical in every frame.
  * Check: the 48 probe values we had measured from received frames (decisions, 2026-09-28) agree with this
    scrambler output at all 48 positions, apart from one constant 180-degree rotation, which is the same overall
    sign difference we had already found for the sync. So our measured template = (this template) x (-1).

Phase convention: 8PSK index k means exp(j*pi*k/4). Sync +1 = index 0, -1 = index 4.
Output: s4285_known_symbols.csv with one row per frame symbol 0..255.
"""
import numpy as np

SYMBOLS_PER_FRAME = 256
SYNC_LENGTH = 80
DATA_PART_LENGTH = 176
PROBE_STARTS_IN_FRAME = (112, 160, 208)
PROBE_LENGTH = 16


def pn31_sync():
    """80 sync symbols: the 31-bit PN sequence (an m-sequence of x^5 + x^2 + 1) repeated, bit 0 -> +1, bit 1 -> -1."""
    pn31_bits = '0101100111110001101110101000010'
    bits = np.array([int(c) for c in pn31_bits])
    repeated = np.concatenate([bits, bits, bits])[:SYNC_LENGTH]
    return 1 - 2 * repeated


def scrambler_indices():
    """176 scrambler outputs (8PSK index 0-7): 9-stage register x^9 + x^4 + 1, all ones, 3 shifts per symbol."""
    register = [1] * 9               # register[0] is the output end
    indices = []
    for n in range(DATA_PART_LENGTH):
        value = register[0] + 2 * register[1] + 4 * register[2]
        indices.append(value)
        for shift in range(3):
            feedback = register[0] ^ register[4]
            register = register[1:] + [feedback]
    return np.array(indices)


def frame_template():
    """Complex value, 8PSK index and role of every one of the 256 frame symbols (unknown data -> NaN)."""
    values = np.full(SYMBOLS_PER_FRAME, np.nan + 1j * np.nan)
    index = np.full(SYMBOLS_PER_FRAME, -1)
    role = np.array(['data'] * SYMBOLS_PER_FRAME, dtype=object)
    sync = pn31_sync()
    values[:SYNC_LENGTH] = sync
    index[:SYNC_LENGTH] = np.where(sync > 0, 0, 4)
    role[:SYNC_LENGTH] = 'sync'
    scrambler = scrambler_indices()
    for start in PROBE_STARTS_IN_FRAME:
        for offset in range(PROBE_LENGTH):
            symbol = start + offset
            k = scrambler[symbol - SYNC_LENGTH]
            values[symbol] = np.exp(1j * np.pi * k / 4)
            index[symbol] = k
            role[symbol] = 'probe'
    return values, index, role


if __name__ == '__main__':
    values, index, role = frame_template()
    with open('s4285_known_symbols.csv', 'w') as f:
        f.write('# STANAG 4285 frame, 256 symbols at 2400 Bd. role: sync (known), probe (known, scrambled), data (unknown).\n')
        f.write('# value = exp(j*pi*k/4); I,Q empty for data. Generated by s4285_known_symbols.py (AB1LD/Claude 2026-10-07).\n')
        f.write('symbol,role,k_8psk,I,Q\n')
        for n in range(SYMBOLS_PER_FRAME):
            if role[n] == 'data':
                f.write(f'{n},data,,,\n')
            else:
                f.write(f'{n},{role[n]},{index[n]},{values[n].real:+.6f},{values[n].imag:+.6f}\n')
    print('wrote s4285_known_symbols.csv')
